In [ ]:
##Name Habib Ahmad Siddiqui
## Roll no 71
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score,confusion_matrix,precision_score,recall_score,f1_score)
from sklearn.preprocessing import StandardScaler,LabelEncoder
from scipy import stats

In [ ]:
##Name Habib Ahmad Siddiqui
## Roll no 71
path = r"C:\\Users\\Habbib Ahmed Sidique\\OneDrive\\Desktop\\AI ML\\Classifications Models\\Logistic Regression\\Breast Cancer Disease Detector Model\\archive\breast-cancer.csv"
Breast_cancer = pd.read_csv(path)
Breast_cancer.head(5)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,1.097064,-2.073335,1.269934,0.984375,1.568466,3.283515,2.652874,2.532475,2.217515,...,1.886690,-1.359293,2.303601,2.001237,1.307686,2.616665,2.109526,2.296076,2.750622,1.937015
1,M,1.829821,-0.353632,1.685955,1.908708,-0.826962,-0.487072,-0.023846,0.548144,0.001392,...,1.805927,-0.369203,1.535126,1.890489,-0.375612,-0.430444,-0.146749,1.087084,-0.243890,0.281190
2,M,1.579888,0.456187,1.566503,1.558884,0.942210,1.052926,1.363478,2.037231,0.939685,...,1.511870,-0.023974,1.347475,1.456285,0.527407,1.082932,0.854974,1.955000,1.152255,0.201391
3,M,-0.768909,0.253732,-0.592687,-0.764464,3.283553,3.402909,1.915897,1.451707,2.867383,...,-0.281464,0.133984,-0.249939,-0.550021,3.394275,3.893397,1.989588,2.175786,6.046041,4.935010
4,M,1.750297,-1.151816,1.776573,1.826229,0.280372,0.539340,1.371011,1.428493,-0.009560,...,1.298575,-1.466770,1.338539,1.220724,0.220556,-0.313395,0.613179,0.729259,-0.868353,-0.397100

In [ ]:
##Name Habib Ahmad Siddiqui
## Roll no 71
df=pd.DataFrame(Breast_cancer)

In [ ]:
##Name Habib Ahmad Siddiqui
## Roll no 71
Breast_cancer.head()
Breast_cancer.tail()
Breast_cancer.shape
Breast_cancer.info()
Breast_cancer.isnull().sum()
Breast_cancer.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    object
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,...,5.690000e+02,5.690000e+02,5.690000e+02,569.000000,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02
mean,-1.373633e-16,7.492542e-17,-1.248757e-16,-2.122887e-16,-8.116921e-16,1.873136e-16,4.995028e-17,-3.746271e-17,1.748260e-16,4.838933e-16,...,-8.491548e-16,1.248757e-17,-3.621395e-16,0.000000,-2.247763e-16,-3.496520e-16,7.492542e-17,2.497514e-16,2.747265e-16,-5.619407e-16
std,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,...,1.000880e+00,1.000880e+00,1.000880e+00,1.000880,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00
min,-2.029648e+00,-2.229249e+00,-1.984504e+00,-1.454443e+00,-3.112085e+00,-1.610136e+00,-1.114873e+00,-1.261820e+00,-2.744117e+00,-1.819865e+00,...,-1.726901e+00,-2.223994e+00,-1.693361e+00,-1.222423,-2.682695e+00,-1.443878e+00,-1.305831e+00,-1.745063e+00,-2.160960e+00,-1.601839e+00
25%,-6.893853e-01,-7.259631e-01,-6.919555e-01,-6.671955e-01,-7.109628e-01,-7.470860e-01,-7.437479e-01,-7.379438e-01,-7.032397e-01,-7.226392e-01,...,-6.749213e-01,-7.486293e-01,-6.895783e-01,-0.642136,-6.912304e-01,-6.810833e-01,-7.565142e-01,-7.563999e-01,-6.418637e-01,-6.919118e-01
50%,-2.150816e-01,-1.046362e-01,-2.359800e-01,-2.951869e-01,-3.489108e-02,-2.219405e-01,-3.422399e-01,-3.977212e-01,-7.162650e-02,-1.782793e-01,...,-2.690395e-01,-4.351564e-02,-2.859802e-01,-0.341181,-4.684277e-02,-2.695009e-01,-2.182321e-01,-2.234689e-01,-1.274095e-01,-2.164441e-01
75%,4.693926e-01,5.841756e-01,4.996769e-01,3.635073e-01,6.361990e-01,4.938569e-01,5.260619e-01,6.469351e-01,5.307792e-01,4.709834e-01,...,5.220158e-01,6.583411e-01,5.402790e-01,0.357589,5.975448e-01,5.396688e-01,5.311411e-01,7.125100e-01,4.501382e-01,4.507624e-01
max,3.971288e+00,4.651889e+00,3.976130e+00,5.250529e+00,4.770911e+00,4.568425e+00,4.243589e+00,3.927930e+00,4.484751e+00,4.910919e+00,...,4.094189e+00,3.885905e+00,4.287337e+00,5.930172,3.955374e+00,5.112877e+00,4.700669e+00,2.685877e+00,6.046041e+00,6.846856e+00

In [ ]:
##Name Habib Ahmad Siddiqui
## Roll no 71
encoder=LabelEncoder()

In [ ]:
##Name Habib Ahmad Siddiqui
## Roll no 71
for col in df.columns:
    if df[col].dtype=='object':
        df[col]=encoder.fit_transform(df[col])

In [ ]:
##Name Habib Ahmad Siddiqui
## Roll no 71
X=df.drop(columns =  'diagnosis')
Y=df['diagnosis']
print(X)
print(Y)

     radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0       1.097064     -2.073335        1.269934   0.984375         1.568466
1       1.829821     -0.353632        1.685955   1.908708        -0.826962
2       1.579888      0.456187        1.566503   1.558884         0.942210
3      -0.768909      0.253732       -0.592687  -0.764464         3.283553
4       1.750297     -1.151816        1.776573   1.826229         0.280372
..           ...           ...             ...        ...              ...
564     2.110995      0.721473        2.060786   2.343856         1.041842
565     1.704854      2.085134        1.615931   1.723842         0.102458
566     0.702284      2.045574        0.672676   0.577953        -0.840484
567     1.838341      2.336457        1.982524   1.735218         1.525767
568    -1.808401      1.221792       -1.814389  -1.347789        -3.112085

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0            3.283515        2.652874             2.532475       2.217515
1           -0.487072       -0.023846             0.548144       0.001392
2            1.052926        1.363478             2.037231       0.939685
3            3.402909        1.915897             1.451707       2.867383
4            0.539340        1.371011             1.428493      -0.009560
..                ...             ...                  ...            ...
564          0.219060        1.947285             2.320965      -0.312589
565         -0.017833        0.693043             1.263669      -0.217664
566         -0.038680        0.046588             0.105777      -0.809117
567          3.272144        3.296944             2.658866       2.137194
568         -1.150752       -1.114873            -1.261820      -0.820070

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                  2.255747  ...      1.886690      -1.359293
1                 -0.868652  ...      1.805927      -0.369203
2                 -0.398008  ...      1.511870      -0.023974
3                  4.910919  ...     -0.281464       0.133984
4                 -0.562450  ...      1.298575      -1.466770
..                      ...  ...           ...            ...
564               -0.931027  ...      1.901185       0.117700
565               -1.058611  ...      1.536720       2.047399
566               -0.895587  ...      0.561361       1.374854
567                1.043695  ...      1.961239       2.237926
568               -0.561032  ...     -1.410893       0.764190

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0           2.303601    2.001237          1.307686           2.616665
1           1.535126    1.890489         -0.375612          -0.430444
2           1.347475    1.456285          0.527407           1.082932
3          -0.249939   -0.550021          3.394275           3.893397
4           1.338539    1.220724          0.220556          -0.313395
..               ...         ...               ...                ...
564         1.752563    2.015301          0.378365          -0.273318
565         1.421940    1.494959         -0.691230          -0.394820
566         0.579001    0.427906         -0.809587           0.350735
567         2.303601    1.653171          1.430427           3.904848
568        -1.432735   -1.075813         -1.859019          -1.207552

     concavity_worst  concave points_worst  symmetry_worst  \
0           2.109526              2.296076        2.750622
1          -0.146749              1.087084       -0.243890
2           0.854974              1.955000        1.152255
3           1.989588              2.175786        6.046041
4           0.613179              0.729259       -0.868353
..               ...                   ...             ...
564         0.664512              1.629151       -1.360158
565         0.236573              0.733827       -0.531855
566         0.326767              0.414069       -1.104549
567         3.197605              2.289985        1.919083
568        -1.305831             -1.745063       -0.048138

     fractal_dimension_worst
0                   1.937015
1                   0.281190
2                   0.201391
3                   4.935010
4                  -0.397100
..                       ...
564                -0.709091
565                -0.973978
566                -0.318409
567                 2.219635
568                -0.751207

[569 rows x 30 columns]
0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64

In [ ]:
##Name Habib Ahmad Siddiqui
## Roll no 71
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)
print(X.shape,X_train.shape,X_test.shape)
model = LogisticRegression()
model.fit(X_train,Y_train)

(569, 30) (455, 30) (114, 30)

LogisticRegression()

In [ ]:
##Name Habib Ahmad Siddiqui
## Roll no 71
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)
print('Accuracy on Training data:',training_data_accuracy)

Accuracy on Training data: 0.989010989010989

In [ ]:
##Name Habib Ahmad Siddiqui
## Roll no 71
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)
print('Accuracy on Test Data:',test_data_accuracy)

Accuracy on Test Data: 0.9824561403508771

In [ ]:
##Name Habib Ahmad Siddiqui
## Roll no 71
cm = confusion_matrix(Y_test,X_test_prediction)
print("confusion_matrix")
print(cm)

confusion_matrix
[[71  0]
 [ 2 41]]

In [ ]:
##Name Habib Ahmad Siddiqui
## Roll no 71
recall = recall_score(Y_test,X_test_prediction)
print("Recall Score is: ")
print(recall)

Recall Score is:
0.9534883720930233

In [ ]:
##Name Habib Ahmad Siddiqui
## Roll no 71
F1_score = f1_score(Y_test,X_test_prediction)
print("F1-Score is: ")
print(F1_score)

F1-Score is:
0.9761904761904762

In [ ]:
##Name Habib Ahmad Siddiqui
## Roll no 71
precise= precision_score(Y_test,X_test_prediction)
print("Precision Score is: ")
print(precise)

Precision Score is:
1.0